#!/bin/bash

set -Eeo pipefail

task="$1"
script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "${script_dir}"

case "${task}" in
  dojo-test)
      dojo -c "${script_dir}/Dojofile" "./tasks test"
      ;;
  test)
      npm ci
      npm run test
      ;;
  *)
      echo "Invalid command: '${task}'"
      exit 1
      ;;
esac

set +e